// ESLint flat config (ESLint 9+). `eslint-config-next` v16 ships flat-config
// arrays directly, so they are spread in rather than wrapped by FlatCompat.
//
// `core-web-vitals` is the Next base plus the perf rules promoted to errors;
// `typescript` layers on typescript-eslint. Project-specific rules follow so
// they win the cascade.
import next from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";
import a11y from "eslint-plugin-jsx-a11y";
import vitest from "@vitest/eslint-plugin";

const config = [
  {
    // Build output, deps, and generated type shims are never linted.
    ignores: [
      ".next/**",
      "node_modules/**",
      // Generated by `npm run test:coverage`; gitignored, and not ours to lint.
      "coverage/**",
      // Stryker's scratch directory and its report. The sandbox holds whole
      // mutated copies of `src`, so linting it means linting deliberately
      // broken code — roughly five hundred errors that are not about anything.
      // Only visible while a mutation run is in flight, which is exactly when
      // a confusing lint failure is hardest to place.
      ".stryker-tmp/**",
      "reports/**",
      "next-env.d.ts",
      "tsconfig.tsbuildinfo",
    ],
  },

  ...next,
  ...nextTypescript,

  {
    // The full jsx-a11y recommended set (34 rules), not the six Next enables by
    // default. The audit found the real accessibility gaps by walking the
    // rendered DOM of every page; these rules are what keeps them from coming
    // back, in CI, on the diff that introduces them.
    //
    // Only the rule map is taken, not `a11y.flatConfigs.recommended` itself:
    // eslint-config-next has already registered the plugin, and a second
    // registration is a hard config error. Reading the map from the package
    // means the set tracks the plugin version rather than a copied list.
    name: "jsx-a11y/recommended-rules",
    rules: a11y.flatConfigs.recommended.rules,
  },

  {
    // The test suite is load-bearing here — coverage floors gate CI and a
    // weekly mutation run gates the assertions themselves — so the tests get
    // linted for the failures that are invisible when they happen. Each rule
    // below is one that makes a suite report success while testing less than
    // it appears to.
    name: "vitest/test-files",
    files: ["**/*.test.ts", "**/*.test.tsx", "src/test/**/*.ts"],
    plugins: { vitest },
    rules: {
      // The worst of them: one committed `.only` silently reduces a file to a
      // single test and CI still reports green.
      "vitest/no-focused-tests": "error",
      // A test with no assertion at all passes unconditionally.
      "vitest/expect-expect": "error",
      // `expect(x)` with no matcher, or a forgotten `await` on an async
      // matcher — both are assertions that never actually assert.
      //
      // `maxArgs: 2` because Vitest, unlike Jest, takes a message as the
      // second argument: `expect(value, "which case failed").toBe(...)`. The
      // default of 1 flags every one of those, and they are worth keeping —
      // inside a loop the message is the only thing identifying which
      // iteration broke.
      "vitest/valid-expect": ["error", { maxArgs: 2 }],
      // Assertions inside a conditional may simply never run, which looks the
      // same as passing.
      "vitest/no-conditional-expect": "error",
      // An `expect` outside a test never runs as part of one.
      "vitest/no-standalone-expect": "error",
      // Two tests with the same name in one describe: the suite reports both,
      // but the duplicate title makes a failure impossible to locate.
      "vitest/no-identical-title": "error",
      // A skipped test is a silent hole. Warn rather than error, since
      // skipping deliberately while investigating is legitimate; it just
      // should not survive a merge unnoticed.
      "vitest/no-disabled-tests": "warn",
      // A commented-out test is a quieter hole than a skipped one: a skip is
      // at least reported as a skip, while this is reported as nothing.
      "vitest/no-commented-out-tests": "error",
      // An `expect` inside a `.then()` on a promise the test never returns or
      // awaits. The test finishes — and passes — before the assertion runs.
      "vitest/valid-expect-in-promise": "error",
      // A `describe` callback containing a `return` statement, which ends
      // registration early and silently leaves out every test below it.
      //
      // Narrower than it sounds, and worth being exact since the obvious
      // reading is wrong: this rule does NOT flag an `async` describe
      // callback. That failure mode — the tests inside registering after the
      // suite has been collected — is not covered by anything in this plugin.
      "vitest/valid-describe-callback": "error",
      // `toMatchSnapshot()` inside `test.concurrent` without taking the local
      // `expect` from the test context: concurrent tests share the global one,
      // so snapshots are matched against the wrong test's state.
      "vitest/require-local-test-context-for-concurrent-snapshots": "error",
    },
  },

  {
    rules: {
      // `_`-prefixed args are the established convention for the deliberately
      // unused callback params in the block/lightbox signatures.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrors: "none",
        },
      ],
      // The rich-text AST is genuinely untyped JSON from Hygraph; the boundary
      // is narrowed by `sanitizeRichTextAst` rather than by the type system.
      "@typescript-eslint/no-explicit-any": "warn",

      // --- React Compiler rules: warn, not error (deliberate, tracked) ---
      //
      // eslint-plugin-react-hooks v7 ships the React Compiler ruleset. Both
      // rules below fire on existing, working code, and silencing them properly
      // means real refactors — not something to smuggle into a tooling change.
      // They stay visible as warnings so new violations are still obvious, and
      // are promoted back to "error" once the existing sites are fixed.
      //
      // `refs`: mostly false positives from the `toolbarButton(icon, label, cb)`
      // helper in RichTextEditor — the rule can't prove the callbacks aren't
      // invoked during render, so every ref-closing callback is flagged.
      "react-hooks/refs": "warn",
      // `set-state-in-effect`: the prop-to-state sync it was pointing at is
      // gone — those six page clients now adjust state during render via
      // `useSyncedState`. The four remaining call sites are SSR mount gates and
      // async data loads, which the rule cannot distinguish from prop
      // derivation; each carries a targeted disable explaining why. Promoted to
      // an error so a genuine new one fails the build.
      "react-hooks/set-state-in-effect": "error",
    },
  },
];

export default config;
