// sitemap.xml.
//
// Two properties here are load-bearing and silent.
//
// The first is that the query asks for no stage. `cmsRead` serves admins the
// DRAFT stage, and a sitemap is generated by whichever request happens to
// trigger it — so a stage variable here would mean an admin browsing the site
// could publish unpublished slugs to search engines. The source says so; only
// the absence of `$stage` enforces it.
//
// The second is that archived projects are excluded. They 404 for the public,
// so listing them advertises broken URLs to crawlers.

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { at } from "@/test/at";

const cmsRead = vi.hoisted(() => vi.fn());

vi.mock("@/lib/cachedReads", () => ({
  cmsRead,
  CACHE_TAGS: { siteData: "siteData", projects: "projects" },
}));

const sitemap = (await import("./sitemap")).default;

const STATIC_PATHS = ["", "/portfolio", "/about", "/atelier", "/contact"];

const urls = async () => (await sitemap()).map((e) => e.url);

beforeEach(() => {
  cmsRead.mockReset();
  cmsRead.mockResolvedValue({ projects: [], siteDatas: [{}] });
  vi.stubEnv("WEBSITE_URL", "https://example.test");
});

afterEach(() => {
  vi.unstubAllEnvs();
});

describe("the query", () => {
  // The whole reason the source calls this out: cmsRead substitutes a stage
  // only into queries that ask for one, so asking for none is what keeps an
  // admin's DRAFT view out of the sitemap.
  it("asks for no stage, so an admin browsing cannot leak unpublished slugs", async () => {
    await sitemap();

    const query = at(cmsRead.mock.calls, 0)[0] as string;
    expect(query).not.toContain("$stage");
    expect(query).not.toContain("stage:");
  });

  it("tags the read so a publish can invalidate it", async () => {
    await sitemap();

    const options = at(cmsRead.mock.calls, 0)[2] as { tags: string[] };
    expect(options.tags).toEqual(expect.arrayContaining(["siteData", "projects"]));
  });
});

describe("the static routes", () => {
  it("lists every top-level page, absolute", async () => {
    expect(await urls()).toEqual(STATIC_PATHS.map((p) => `https://example.test${p}`));
  });

  it.each(["https://example.test/", "https://example.test", "https://example.test//", "  https://example.test/  "])(
    "does not double the slash for the configured url %j",
    async (url) => {
      vi.stubEnv("WEBSITE_URL", url);

      for (const entry of await urls()) {
        expect(entry).not.toMatch(/(?<!:)\/\//);
      }
    }
  );

  // Same normalization as robots.ts, and it has to be: robots advertises
  // `${base}/sitemap.xml`, so a base that differed here would point crawlers
  // at a URL this file does not serve.
  it.each(["  https://example.test  ", "https://example.test//"])(
    "normalizes %j to the same origin robots advertises",
    async (url) => {
      vi.stubEnv("WEBSITE_URL", url);
      expect(at(await urls(), 1)).toBe("https://example.test/portfolio");
    }
  );

  it("gives every entry a lastModified date", async () => {
    for (const entry of await sitemap()) {
      expect(entry.lastModified).toBeInstanceOf(Date);
    }
  });
});

describe("the project routes", () => {
  const projects = [
    { id: "a", slug: "alpha", updatedAt: "2026-01-01T00:00:00.000Z" },
    { id: "b", slug: "beta", updatedAt: "2026-02-02T00:00:00.000Z" },
  ];

  it("lists each published project under /portfolio", async () => {
    cmsRead.mockResolvedValue({ projects, siteDatas: [{}] });

    expect(await urls()).toEqual([
      ...STATIC_PATHS.map((p) => `https://example.test${p}`),
      "https://example.test/portfolio/alpha",
      "https://example.test/portfolio/beta",
    ]);
  });

  // Archived projects 404 for the public, so listing them advertises broken
  // URLs to crawlers.
  it("excludes an archived project", async () => {
    cmsRead.mockResolvedValue({
      projects,
      siteDatas: [{ portfolio: { entries: [{ id: "a", archived: true }] } }],
    });

    const result = await urls();
    expect(result).not.toContain("https://example.test/portfolio/alpha");
    expect(result).toContain("https://example.test/portfolio/beta");
  });

  it("uses the configured order rather than the CMS's", async () => {
    cmsRead.mockResolvedValue({
      projects,
      siteDatas: [{ portfolio: { entries: [{ id: "b" }, { id: "a" }] } }],
    });

    expect((await urls()).slice(STATIC_PATHS.length)).toEqual([
      "https://example.test/portfolio/beta",
      "https://example.test/portfolio/alpha",
    ]);
  });

  it("reports each project's own updatedAt as its lastModified", async () => {
    cmsRead.mockResolvedValue({ projects, siteDatas: [{}] });

    const entries = await sitemap();
    expect(at(entries, STATIC_PATHS.length).lastModified).toEqual(new Date(projects[0]!.updatedAt));
  });

  it("falls back to now for a project with no updatedAt", async () => {
    cmsRead.mockResolvedValue({ projects: [{ id: "a", slug: "alpha" }], siteDatas: [{}] });

    const entry = at(await sitemap(), STATIC_PATHS.length);
    expect(entry.lastModified).toBeInstanceOf(Date);
  });
});

describe("when the CMS is unreachable", () => {
  // A sitemap that 500s is worse than one listing only the static pages: the
  // crawler drops what it already knew.
  it("still serves the static routes", async () => {
    cmsRead.mockRejectedValue(new Error("CMS down"));

    expect(await urls()).toEqual(STATIC_PATHS.map((p) => `https://example.test${p}`));
  });

  it.each([
    ["a null response", null],
    ["no projects key", { siteDatas: [{}] }],
    ["a null projects value", { projects: null, siteDatas: [{}] }],
    ["no siteDatas", { projects: [] }],
    ["a malformed portfolio config", { projects: [], siteDatas: [{ portfolio: "nope" }] }],
  ])("survives %s", async (_n, payload) => {
    cmsRead.mockResolvedValue(payload);

    expect(await urls()).toEqual(STATIC_PATHS.map((p) => `https://example.test${p}`));
  });
});
